### ISSUE TITLE
update-submodule: submodule should be updated to fetched ref rather that ref

### ISSUE THREAD

**Issue by ylobankov** [tarantool/actions#44]
The current code in the action:

```yml
    - name: Create the new branch and push changes
      id: create-branch
      shell: bash
      run: |
        pushd ${{ inputs.submodule }}
        git fetch origin ${{ inputs.update_to }}
        git checkout ${{ inputs.update_to }}
        popd
```

The `git checkout ${{ inputs.update_to }}` will not give us the desired result when the target repository is already checked out on a self-hosted runner. Looks like we should check out fetched ref instead of ref.
